name: Update NeetCode Tracker

on:
  push:
    paths:
      - 'progress.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run update script
        run: |
          python .github/scripts/generate_readme.py

      - name: Commit and push
        run: |
          git config --global user.name "amistry08"
          git config --global user.email "ayushmistry1998@gmail.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "Update NeetCode progress" || echo "No changes"
          git push origin HEAD:main
